# The ninja build target of the homework (or the name of the executable)
# If not provided, defaults to the name of the homework (which is the name of the .toml file)
target = "hw2"

# The absolute path runner for the homework
runner = "/home/ipc20/ta/hw2/runner.py"

# Files to copy before compiling
files = [
    {name = "hw2.cc"},
    {name = "build.ninja", fallback = "/home/ipc20/ta/hw2/build.ninja"},
]

# Time penalty for failing a test case
penalty_time = 1800

# Name of the test cases
cases = [
    "[01-5].txt"
]
