// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: scoreboard.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QueryHomeworkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *QueryHomeworkRequest) Reset() {
	*x = QueryHomeworkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreboard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryHomeworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHomeworkRequest) ProtoMessage() {}

func (x *QueryHomeworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHomeworkRequest.ProtoReflect.Descriptor instead.
func (*QueryHomeworkRequest) Descriptor() ([]byte, []int) {
	return file_scoreboard_proto_rawDescGZIP(), []int{0}
}

func (x *QueryHomeworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Homework struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target      string        `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Runner      string        `protobuf:"bytes,3,opt,name=runner,proto3" json:"runner,omitempty"`
	Files       []*SourceFile `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	PenaltyTime float64       `protobuf:"fixed64,5,opt,name=penalty_time,json=penaltyTime,proto3" json:"penalty_time,omitempty"`
	Cases       []string      `protobuf:"bytes,6,rep,name=cases,proto3" json:"cases,omitempty"`
}

func (x *Homework) Reset() {
	*x = Homework{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreboard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Homework) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Homework) ProtoMessage() {}

func (x *Homework) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Homework.ProtoReflect.Descriptor instead.
func (*Homework) Descriptor() ([]byte, []int) {
	return file_scoreboard_proto_rawDescGZIP(), []int{1}
}

func (x *Homework) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Homework) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Homework) GetRunner() string {
	if x != nil {
		return x.Runner
	}
	return ""
}

func (x *Homework) GetFiles() []*SourceFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Homework) GetPenaltyTime() float64 {
	if x != nil {
		return x.PenaltyTime
	}
	return 0
}

func (x *Homework) GetCases() []string {
	if x != nil {
		return x.Cases
	}
	return nil
}

type SourceFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fallback string `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
}

func (x *SourceFile) Reset() {
	*x = SourceFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreboard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceFile) ProtoMessage() {}

func (x *SourceFile) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceFile.ProtoReflect.Descriptor instead.
func (*SourceFile) Descriptor() ([]byte, []int) {
	return file_scoreboard_proto_rawDescGZIP(), []int{2}
}

func (x *SourceFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SourceFile) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

type SubmissionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SubmissionReply) Reset() {
	*x = SubmissionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreboard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmissionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmissionReply) ProtoMessage() {}

func (x *SubmissionReply) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmissionReply.ProtoReflect.Descriptor instead.
func (*SubmissionReply) Descriptor() ([]byte, []int) {
	return file_scoreboard_proto_rawDescGZIP(), []int{3}
}

func (x *SubmissionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StoredSubmission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User    string    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Results []*Result `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *StoredSubmission) Reset() {
	*x = StoredSubmission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreboard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoredSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredSubmission) ProtoMessage() {}

func (x *StoredSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredSubmission.ProtoReflect.Descriptor instead.
func (*StoredSubmission) Descriptor() ([]byte, []int) {
	return file_scoreboard_proto_rawDescGZIP(), []int{4}
}

func (x *StoredSubmission) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StoredSubmission) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type UserSubmission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// string secret = 2;
	Homework string    `protobuf:"bytes,3,opt,name=homework,proto3" json:"homework,omitempty"`
	Results  []*Result `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	Code     []byte    `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *UserSubmission) Reset() {
	*x = UserSubmission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreboard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubmission) ProtoMessage() {}

func (x *UserSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubmission.ProtoReflect.Descriptor instead.
func (*UserSubmission) Descriptor() ([]byte, []int) {
	return file_scoreboard_proto_rawDescGZIP(), []int{5}
}

func (x *UserSubmission) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserSubmission) GetHomework() string {
	if x != nil {
		return x.Homework
	}
	return ""
}

func (x *UserSubmission) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *UserSubmission) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Case    string  `protobuf:"bytes,1,opt,name=case,proto3" json:"case,omitempty"`
	Passed  bool    `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Time    float64 `protobuf:"fixed64,3,opt,name=time,proto3" json:"time,omitempty"`
	Verdict string  `protobuf:"bytes,4,opt,name=verdict,proto3" json:"verdict,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scoreboard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_scoreboard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_scoreboard_proto_rawDescGZIP(), []int{6}
}

func (x *Result) GetCase() string {
	if x != nil {
		return x.Case
	}
	return ""
}

func (x *Result) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *Result) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Result) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

var File_scoreboard_proto protoreflect.FileDescriptor

var file_scoreboard_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2a, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48,
	0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xad, 0x01, 0x0a, 0x08, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x75, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x6e,
	0x6e, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x65, 0x6e,
	0x61, 0x6c, 0x74, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x70, 0x65, 0x6e, 0x61, 0x6c, 0x74, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x61, 0x73, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x73,
	0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x22, 0x2b, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x4c, 0x0a,
	0x10, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x7a, 0x0a, 0x0e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x24, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x62, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x70, 0x61, 0x73, 0x73, 0x65, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x64, 0x69, 0x63, 0x74, 0x32, 0x7c, 0x0a, 0x0a, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x39,
	0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x48, 0x6f, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x48,
	0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_scoreboard_proto_rawDescOnce sync.Once
	file_scoreboard_proto_rawDescData = file_scoreboard_proto_rawDesc
)

func file_scoreboard_proto_rawDescGZIP() []byte {
	file_scoreboard_proto_rawDescOnce.Do(func() {
		file_scoreboard_proto_rawDescData = protoimpl.X.CompressGZIP(file_scoreboard_proto_rawDescData)
	})
	return file_scoreboard_proto_rawDescData
}

var file_scoreboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scoreboard_proto_goTypes = []interface{}{
	(*QueryHomeworkRequest)(nil), // 0: pb.QueryHomeworkRequest
	(*Homework)(nil),             // 1: pb.Homework
	(*SourceFile)(nil),           // 2: pb.SourceFile
	(*SubmissionReply)(nil),      // 3: pb.SubmissionReply
	(*StoredSubmission)(nil),     // 4: pb.StoredSubmission
	(*UserSubmission)(nil),       // 5: pb.UserSubmission
	(*Result)(nil),               // 6: pb.Result
}
var file_scoreboard_proto_depIdxs = []int32{
	2, // 0: pb.Homework.files:type_name -> pb.SourceFile
	6, // 1: pb.StoredSubmission.results:type_name -> pb.Result
	6, // 2: pb.UserSubmission.results:type_name -> pb.Result
	5, // 3: pb.Scoreboard.Submit:input_type -> pb.UserSubmission
	0, // 4: pb.Scoreboard.QueryHomework:input_type -> pb.QueryHomeworkRequest
	3, // 5: pb.Scoreboard.Submit:output_type -> pb.SubmissionReply
	1, // 6: pb.Scoreboard.QueryHomework:output_type -> pb.Homework
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_scoreboard_proto_init() }
func file_scoreboard_proto_init() {
	if File_scoreboard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scoreboard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryHomeworkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreboard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Homework); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreboard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreboard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmissionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreboard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoredSubmission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreboard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSubmission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scoreboard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scoreboard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scoreboard_proto_goTypes,
		DependencyIndexes: file_scoreboard_proto_depIdxs,
		MessageInfos:      file_scoreboard_proto_msgTypes,
	}.Build()
	File_scoreboard_proto = out.File
	file_scoreboard_proto_rawDesc = nil
	file_scoreboard_proto_goTypes = nil
	file_scoreboard_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ScoreboardClient is the client API for Scoreboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScoreboardClient interface {
	Submit(ctx context.Context, in *UserSubmission, opts ...grpc.CallOption) (*SubmissionReply, error)
	QueryHomework(ctx context.Context, in *QueryHomeworkRequest, opts ...grpc.CallOption) (*Homework, error)
}

type scoreboardClient struct {
	cc grpc.ClientConnInterface
}

func NewScoreboardClient(cc grpc.ClientConnInterface) ScoreboardClient {
	return &scoreboardClient{cc}
}

func (c *scoreboardClient) Submit(ctx context.Context, in *UserSubmission, opts ...grpc.CallOption) (*SubmissionReply, error) {
	out := new(SubmissionReply)
	err := c.cc.Invoke(ctx, "/pb.Scoreboard/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoreboardClient) QueryHomework(ctx context.Context, in *QueryHomeworkRequest, opts ...grpc.CallOption) (*Homework, error) {
	out := new(Homework)
	err := c.cc.Invoke(ctx, "/pb.Scoreboard/QueryHomework", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoreboardServer is the server API for Scoreboard service.
type ScoreboardServer interface {
	Submit(context.Context, *UserSubmission) (*SubmissionReply, error)
	QueryHomework(context.Context, *QueryHomeworkRequest) (*Homework, error)
}

// UnimplementedScoreboardServer can be embedded to have forward compatible implementations.
type UnimplementedScoreboardServer struct {
}

func (*UnimplementedScoreboardServer) Submit(context.Context, *UserSubmission) (*SubmissionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (*UnimplementedScoreboardServer) QueryHomework(context.Context, *QueryHomeworkRequest) (*Homework, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryHomework not implemented")
}

func RegisterScoreboardServer(s *grpc.Server, srv ScoreboardServer) {
	s.RegisterService(&_Scoreboard_serviceDesc, srv)
}

func _Scoreboard_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSubmission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreboardServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scoreboard/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreboardServer).Submit(ctx, req.(*UserSubmission))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scoreboard_QueryHomework_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHomeworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoreboardServer).QueryHomework(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scoreboard/QueryHomework",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoreboardServer).QueryHomework(ctx, req.(*QueryHomeworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scoreboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Scoreboard",
	HandlerType: (*ScoreboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _Scoreboard_Submit_Handler,
		},
		{
			MethodName: "QueryHomework",
			Handler:    _Scoreboard_QueryHomework_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scoreboard.proto",
}
